name: Next.js Deployment

on:
  push:
    branches: [main]

jobs:
  setup:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

  install:
    needs: setup
    runs-on: self-hosted

    steps:
      - run: npm ci

  build:
    needs: install
    runs-on: self-hosted

    steps:
      - run: |
          echo "${{ secrets.ENV_FILE }}" > .env.local
      - run: npm run build --if-present
